module.exports = {
    arrowParens: 'always',
    jsxBracketSameLine: false,
    endOfLine: 'lf',
    printWidth: 90,
    singleQuote: true,
    jsxSingleQuote: true,
    bracketSpacing: true,
    semi: true,
    useTabs: false,
    tabWidth: 4,
    trailingComma: 'all',
    importOrderSeparation: false,
    importOrderSortSpecifiers: true,
    importOrderParserPlugins: ['typescript', 'jsx', 'topLevelAwait'],
};
